from tkinter import *
a=Tk()
a.title("Intro")
a.geometry('1000x1000')
frame=Frame(a,bg="White",bd=5,relief="solid")
frame.place(x=0,y=0,width=1275,height=1275)
l=Label(a,text="Home Page",justify="right",font=("snap itc","22","bold"),relief='solid')
l.place(x=480,y=0)
l=Label(a,text="Username",justify="left",font=("Ebrima","16"),bg="pink",relief='groove')
l.place(x=10,y=50)
user=Entry(a,width=20,justify='center',font=("Erac Bold ITC","16"))
user.place(x=160,y=55)
l=Label(a,text="Password",justify="left",font=("Ebrima","16"),bg="pink",relief='groove')
l.place(x=10,y=100)
user=Entry(a,width=20,justify='center',show="*",font=("Erac Bold ITC","16"))
user.place(x=160,y=100)
l=Label(a,text="Email",justify="left",font=("Ebrima","16"),bg="pink",relief='groove')
l.place(x=10,y=150)
user=Entry(a,width=20,justify='center',font=("Erac Bold ITC","16"))
user.place(x=160,y=150)
l1=Button(a,text="Next",font=("Ebrima","16","bold"),bg="#AEE2FF",relief="raised")
l1.place(x=650,y=200)
l1=Button(a,text="Cancel",font=("Ebrima","16","bold"),bg="#AEE2FF",relief="raised")
l1.place(x=750,y=200)


